// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  AUTH_MANAGER: ServiceStub<import('../auth-manager/index.js').default>;
  CALL_ME_BACK_DB: SmartSql;
  CALL_ORCHESTRATOR: ServiceStub<import('../call-orchestrator/index.js').default>;
  CALL_TRANSCRIPTS: SmartBucket;
  CONVERSATION_MEMORY: SmartMemory;
  logger: Logger;
  mem: KvCache;
  PAYMENT_PROCESSOR: ServiceStub<import('../payment-processor/index.js').default>;
  PERSONA_MANAGER: ServiceStub<import('../persona-manager/index.js').default>;
  RATE_LIMIT_CACHE: KvCache;
  TOKEN_BLACKLIST: KvCache;
  tracer: Tracer;
  VOICE_PIPELINE: ServiceStub<import('../voice-pipeline/index.js').default>;
}
