// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  ADMIN_DASHBOARD: ServiceStub<import('../admin-dashboard/index.js').default>;
  ADMIN_SECRET_TOKEN: string;
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  AUTH_MANAGER: ServiceStub<import('../auth-manager/index.js').default>;
  CALL_ME_BACK_DB: SmartSql;
  CALL_ME_BACK_LOGS: SmartBucket;
  CALL_ORCHESTRATOR: ServiceStub<import('../call-orchestrator/index.js').default>;
  CALL_TRANSCRIPTS: SmartBucket;
  CEREBRAS_API_KEY: string;
  CONVERSATION_MEMORY: SmartMemory;
  COST_ANALYTICS: ServiceStub<import('../cost-analytics/index.js').default>;
  DATABASE_PROXY: ServiceStub<import('../database-proxy/index.js').default>;
  DEEPGRAM_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  FRONTEND_URL: string;
  JWT_SECRET: string;
  LOG_QUERY_SERVICE_URL: string;
  logger: Logger;
  mem: KvCache;
  PAYMENT_PROCESSOR: ServiceStub<import('../payment-processor/index.js').default>;
  PERSONA_MANAGER: ServiceStub<import('../persona-manager/index.js').default>;
  RATE_LIMIT_CACHE: KvCache;
  STRIPE_PRICE_FIFTY_MIN: string;
  STRIPE_PRICE_ONE_HUNDRED_MIN: string;
  STRIPE_PRICE_TWENTY_FIVE_MIN: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  TOKEN_BLACKLIST: KvCache;
  tracer: Tracer;
  TWILIO_ACCOUNT_SID: string;
  TWILIO_AUTH_TOKEN: string;
  TWILIO_PHONE_NUMBER: string;
  USER_DATA: KvCache;
  VOICE_PIPELINE: ServiceStub<import('../voice-pipeline/index.js').default>;
  VULTR_DB_API_KEY: string;
  VULTR_DB_API_URL: string;
  WEBHOOK_HANDLER: ServiceStub<import('../webhook-handler/index.js').default>;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
}
