// Code generated by raindrop build, DO NOT EDIT.
import type { Env } from './raindrop.gen.js';
import { createMockKvCache, createMockLogger, createMockTracer,  } from '@liquidmetal-ai/raindrop-framework/testing';
import type { ActorId, ActorStub, ActorNamespace, Actor, ServiceStub, Service, Ai, Annotation, SqlDatabase, SqlPreparedStatement, SqlResult, SqlExecResult, VectorIndex, SmartBucket, SmartMemory, SmartSql, Payments } from '@liquidmetal-ai/raindrop-framework';
import { vi } from 'vitest';

// ============================================================================
// Inline Mock Utilities (temporary until raindrop-framework is published)
// ============================================================================

/**
 * Creates a mock ServiceStub with stable method mocks
 * Same property access returns same mock instance
 */
function createServiceStubMock<T extends Service<any>>(): ServiceStub<T> {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as ServiceStub<T>, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue(undefined));
      }
      return mockCache.get(prop);
    }
  });
}

/**
 * Creates a mock Ai binding with stable method mocks
 */
function createMockAi(): Ai {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as Ai, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue({}));
      }
      return mockCache.get(prop);
    }
  }) as Ai;
}

/**
 * Creates a mock Annotation binding
 */
function createMockAnnotation<T = any>(): Annotation<T> {
  return {
    get: vi.fn().mockResolvedValue(null),
    put: vi.fn().mockResolvedValue(undefined),
    log: vi.fn().mockResolvedValue(undefined),
    list: vi.fn().mockResolvedValue({ objects: [] }),
    delete: vi.fn().mockResolvedValue(undefined),
  } as Annotation<T>;
}

/**
 * Query handler for fluent mock configuration
 */
interface MockQueryHandler {
  /** Configure first() to return data (single row or null) */
  first(data: Record<string, unknown> | null): MockQueryHandler;
  /** Configure all() to return multiple rows */
  all(rows: Record<string, unknown>[]): MockQueryHandler;
  /** Configure run() success (for INSERT/UPDATE/DELETE) */
  run(result?: { success?: true; changes?: number; lastRowId?: number }): MockQueryHandler;
  /** Configure to throw an error */
  throws(error: Error): MockQueryHandler;
  /** Configure multiple sequential responses for first() - cycles through on each call */
  firstSequence(...results: (Record<string, unknown> | null)[]): MockQueryHandler;
}

/**
 * Extended SqlDatabase mock with fluent query-routing API
 */
interface MockSqlDatabase extends SqlDatabase {
  /**
   * Configure mock responses for queries matching a pattern.
   * Pattern matching uses string.includes() for flexibility.
   *
   * @example
   * ```typescript
   * // Setup ownership check
   * env.DB.whenQuery('SELECT user_id FROM lists').first({ user_id: 'user-123' });
   *
   * // Setup insert to succeed
   * env.DB.whenQuery('INSERT INTO items').run({ success: true });
   *
   * // Setup query to return multiple rows
   * env.DB.whenQuery('SELECT * FROM items').all([
   *   { id: '1', title: 'Item 1' },
   *   { id: '2', title: 'Item 2' },
   * ]);
   *
   * // Setup sequential responses (for ownership check then fetch)
   * env.DB.whenQuery('SELECT').firstSequence(
   *   { user_id: 'user-123' },  // 1st call: ownership check
   *   { id: 'item-1', title: 'Buy milk' }  // 2nd call: fetch result
   * );
   * ```
   */
  whenQuery(pattern: string): MockQueryHandler;

  /**
   * Clear all query handlers (call in beforeEach to reset state)
   */
  resetQueryHandlers(): void;

  /**
   * Get all queries that were executed (for assertions)
   */
  getExecutedQueries(): Array<{ query: string; boundValues: unknown[] }>;
}

/**
 * Creates a mock SqlDatabase with fluent query-routing API
 *
 * Supports two patterns:
 * 1. Fluent API (recommended): env.DB.whenQuery('SELECT').first({ ... })
 * 2. Manual override: env.DB.prepare.mockImplementation((query) => { ... })
 *
 * @example
 * ```typescript
 * const env = createMockEnv();
 *
 * // Pattern 1: Fluent API (clean and readable)
 * env.DB.whenQuery('SELECT user_id FROM lists').first({ user_id: 'user-123' });
 * env.DB.whenQuery('INSERT INTO items').run({ success: true });
 * env.DB.whenQuery('SELECT * FROM items').all([{ id: '1', title: 'Item 1' }]);
 *
 * // Pattern 2: Manual override (full control)
 * env.DB.prepare.mockImplementation((query: string) => {
 *   if (query.includes('SELECT user_id')) {
 *     return { bind: vi.fn().mockReturnValue({ first: vi.fn().mockResolvedValue({ user_id: 'user-123' }) }) };
 *   }
 *   // ... more handlers
 * });
 * ```
 */
function createMockSqlDatabase(): MockSqlDatabase {
  type QueryConfig = {
    firstResult?: Record<string, unknown> | null;
    firstSequence?: (Record<string, unknown> | null)[];
    firstSequenceIndex?: number;
    allResult?: Record<string, unknown>[];
    runResult?: { success: true; meta: SqlResult['meta'] };
    error?: Error;
  };

  const queryHandlers = new Map<string, QueryConfig>();
  const executedQueries: Array<{ query: string; boundValues: unknown[] }> = [];
  const defaultMeta = {
    duration: 0,
    size_after: 0,
    rows_read: 0,
    rows_written: 0,
    last_row_id: 0,
    changed_db: false,
    changes: 0,
  };

  const findHandler = (query: string): QueryConfig | undefined => {
    for (const [pattern, config] of queryHandlers) {
      if (query.includes(pattern)) {
        return config;
      }
    }
    return undefined;
  };

  const createPreparedStatement = (query: string): SqlPreparedStatement => {
    let boundValues: unknown[] = [];

    const mockPrepared: SqlPreparedStatement = {
      query,
      bind: vi.fn((...values: unknown[]) => {
        boundValues = values;
        executedQueries.push({ query, boundValues: values });
        return mockPrepared;
      }),
      first: vi.fn(async () => {
        const handler = findHandler(query);
        if (handler?.error) throw handler.error;
        if (handler?.firstSequence) {
          const index = handler.firstSequenceIndex ?? 0;
          handler.firstSequenceIndex = index + 1;
          return handler.firstSequence[index % handler.firstSequence.length] ?? null;
        }
        return handler?.firstResult ?? null;
      }),
      run: vi.fn(async () => {
        const handler = findHandler(query);
        if (handler?.error) throw handler.error;
        return handler?.runResult ?? { success: true as const, meta: defaultMeta, results: [] };
      }) as SqlPreparedStatement['run'],
      all: vi.fn(async () => {
        const handler = findHandler(query);
        if (handler?.error) throw handler.error;
        return {
          success: true as const,
          meta: defaultMeta,
          results: handler?.allResult ?? []
        };
      }) as SqlPreparedStatement['all'],
      raw: vi.fn().mockResolvedValue([]),
    };

    return mockPrepared;
  };

  const whenQuery = (pattern: string): MockQueryHandler => {
    const config: QueryConfig = {};
    queryHandlers.set(pattern, config);

    const handler: MockQueryHandler = {
      first(data) {
        config.firstResult = data;
        return handler;
      },
      all(rows) {
        config.allResult = rows;
        return handler;
      },
      run(result = {}) {
        config.runResult = {
          success: result.success ?? true,
          meta: {
            ...defaultMeta,
            changes: result.changes ?? 0,
            last_row_id: result.lastRowId ?? 0,
          }
        };
        return handler;
      },
      throws(error) {
        config.error = error;
        return handler;
      },
      firstSequence(...results) {
        config.firstSequence = results;
        config.firstSequenceIndex = 0;
        return handler;
      },
    };

    return handler;
  };

  return {
    prepare: vi.fn((query: string) => createPreparedStatement(query)),
    batch: vi.fn().mockResolvedValue([]),
    exec: vi.fn().mockResolvedValue({ count: 0, duration: 0 } as SqlExecResult),
    whenQuery,
    resetQueryHandlers() {
      queryHandlers.clear();
      executedQueries.length = 0;
    },
    getExecutedQueries() {
      return [...executedQueries];
    },
  } as MockSqlDatabase;
}

/**
 * Creates a mock VectorIndex binding
 */
function createMockVectorIndex(): VectorIndex {
  return {
    describe: vi.fn().mockResolvedValue({
      vectorCount: 0,
      dimensions: 384,
      processedUpToDatetime: Date.now(),
      processedUpToMutation: 0,
    }),
    query: vi.fn().mockResolvedValue({ matches: [], count: 0 }),
    queryById: vi.fn().mockResolvedValue({ matches: [], count: 0 }),
    insert: vi.fn().mockResolvedValue({ mutationId: 'test-mutation' }),
    upsert: vi.fn().mockResolvedValue({ mutationId: 'test-mutation' }),
    deleteByIds: vi.fn().mockResolvedValue({ mutationId: 'test-mutation' }),
    getByIds: vi.fn().mockResolvedValue([]),
  } as VectorIndex;
}

/**
 * Creates a mock SmartBucket with stable method mocks
 */
function createMockSmartBucket(): SmartBucket {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as SmartBucket, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue({}));
      }
      return mockCache.get(prop);
    }
  }) as SmartBucket;
}

/**
 * Creates a mock SmartMemory with stable method mocks
 */
function createMockSmartMemory(): SmartMemory {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as SmartMemory, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue({}));
      }
      return mockCache.get(prop);
    }
  }) as SmartMemory;
}

/**
 * Creates a mock SmartSql with stable method mocks
 */
function createMockSmartSql(): SmartSql {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as SmartSql, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue({}));
      }
      return mockCache.get(prop);
    }
  }) as SmartSql;
}

/**
 * Creates a mock Payments with stable method mocks
 */
function createMockPayments(): Payments {
  const mockCache = new Map<string | symbol, any>();

  return new Proxy({} as Payments, {
    get(_target, prop) {
      if (typeof prop === 'symbol') return undefined;

      if (!mockCache.has(prop)) {
        mockCache.set(prop, vi.fn().mockResolvedValue({}));
      }
      return mockCache.get(prop);
    }
  }) as Payments;
}

// ============================================================================
// Mock Environment Factory
// ============================================================================

/**
 * Creates a fully mocked Env for testing this handler
 * All mocks are stable - the same method returns the same mock on repeated access
 *
 * @param overrides Partial Env to override specific mocks
 * @returns Complete mock Env for testing
 *
 * @example
 * ```typescript
 * import { createMockEnv } from './raindrop.gen.mocks.js';
 *
 * test('my handler', async () => {
 *   const env = createMockEnv();
 *
 *   // Customize specific mocks
 *   env.logger.info.mockImplementation((msg) => console.log(msg));
 *   
 *   
 *
 *   // Setup service mocks
 *   env.API.fetchUser.mockResolvedValue({ id: 1, name: 'Test' });
 *   
 *   
 *
 *   // ... test your handler
 * });
 * ```
 */
export function createMockEnv(overrides?: Partial<Env>): Env {
  return {
    _raindrop: {
      app: {
        organizationId: 'test-org',
        applicationName: 'test-app',
        versionId: 'test-version',
        scriptName: 'test-script',
        visibility: 'public' as const,
      },
    },
    ADMIN_DASHBOARD: createServiceStubMock(),
    ADMIN_SECRET_TOKEN: '',
    AI: createMockAi(),
    annotation: createMockAnnotation(),
    API_GATEWAY: createServiceStubMock(),
    AUTH_MANAGER: createServiceStubMock(),
    CALL_ME_BACK_DB: createMockSmartSql(),
    CALL_ME_BACK_LOGS: createMockSmartBucket(),
    CALL_ORCHESTRATOR: createServiceStubMock(),
    CALL_TRANSCRIPTS: createMockSmartBucket(),
    CEREBRAS_API_KEY: '',
    CONVERSATION_MEMORY: createMockSmartMemory(),
    COST_ANALYTICS: createServiceStubMock(),
    DATABASE_PROXY: createServiceStubMock(),
    DEEPGRAM_API_KEY: '',
    ELEVENLABS_API_KEY: '',
    FRONTEND_URL: '',
    JWT_SECRET: '',
    LOG_QUERY_SERVICE_URL: '',
    logger: createMockLogger(),
    mem: createMockKvCache(),
    PAYMENT_PROCESSOR: createServiceStubMock(),
    PERSONA_MANAGER: createServiceStubMock(),
    RATE_LIMIT_CACHE: createMockKvCache(),
    STRIPE_PRICE_FIFTY_MIN: '',
    STRIPE_PRICE_ONE_HUNDRED_MIN: '',
    STRIPE_PRICE_TWENTY_FIVE_MIN: '',
    STRIPE_SECRET_KEY: '',
    STRIPE_WEBHOOK_SECRET: '',
    TOKEN_BLACKLIST: createMockKvCache(),
    tracer: createMockTracer(),
    TWILIO_ACCOUNT_SID: '',
    TWILIO_AUTH_TOKEN: '',
    TWILIO_PHONE_NUMBER: '',
    TWILIO_VERIFY_SERVICE_SID: '',
    USER_DATA: createMockKvCache(),
    VOICE_PIPELINE: createServiceStubMock(),
    VULTR_DB_API_KEY: '',
    VULTR_DB_API_URL: '',
    WEBHOOK_HANDLER: createServiceStubMock(),
    WORKOS_API_KEY: '',
    WORKOS_CLIENT_ID: '',
    WORKOS_USER_REDIRECT_URI: '',
    ...overrides,
  };
}
