// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SmartSql, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  AUTH_MANAGER: ServiceStub<import('../auth-manager/index.js').default>;
  CALL_ME_BACK_DB: SmartSql;
  CALL_ORCHESTRATOR: ServiceStub<import('../call-orchestrator/index.js').default>;
  CALL_TRANSCRIPTS: SmartBucket;
  CEREBRAS_API_KEY: string;
  CONVERSATION_MEMORY: SmartMemory;
  DEEPGRAM_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  JWT_SECRET: string;
  logger: Logger;
  mem: KvCache;
  PAYMENT_PROCESSOR: ServiceStub<import('../payment-processor/index.js').default>;
  PERSONA_MANAGER: ServiceStub<import('../persona-manager/index.js').default>;
  RATE_LIMIT_CACHE: KvCache;
  TOKEN_BLACKLIST: KvCache;
  tracer: Tracer;
  TWILIO_ACCOUNT_SID: string;
  TWILIO_AUTH_TOKEN: string;
  TWILIO_PHONE_NUMBER: string;
  VOICE_PIPELINE: ServiceStub<import('../voice-pipeline/index.js').default>;
  VULTR_DB_API_KEY: string;
  VULTR_DB_API_URL: string;
  WEBHOOK_HANDLER: ServiceStub<import('../webhook-handler/index.js').default>;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
}
